#!/bin/bash
#安装puppet-master
MASTER_NAME=`hostname -f`

if [[ $? != 0 ]];then
    echo "cannot get fqdn"
    exit 1
fi

read -p "the full hostname is $MASTER_NAME, continue?[y/n]" ret
if [[ ret == 'n' ]];then
    exit 1
fi

wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
dpkg -i puppetlabs-release-trusty.deb && rm  -f puppetlabs-release-trusty.deb

wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
dpkg -i puppetlabs-release-pc1-trusty.deb && rm -f puppetlabs-release-pc1-trusty.deb

if [[ $? != 0 ]];then
    echo 'install puppet  repo failed'
    exit 1
fi
apt-get update && apt-get install -y puppetmaster-passenger


if [[ $? != 0 ]];then
    echo 'install puppet failed'
    exit 1
fi

chown -R puppet:puppet /etc/puppet
chown -R puppet:puppet /var/lib/puppet

#初始puppet.conf
cat > /etc/puppet/puppet.conf <<EOF
[main]
logdir=/var/log/puppet
vardir=/var/lib/puppet
ssldir=/var/lib/puppet/ssl
rundir=/var/run/puppet
factpath=\$vardir/lib/facter
templatedir=\$confdir/templates
dns_alt_names=$MASTER_NAME
server=$MASTER_NAME
environmentpath=/etc/puppet/environments
report=true

[master]
# These are needed when the puppetmaster is run by passenger
# and can safely be removed if webrick is used.
ssl_client_header = SSL_CLIENT_S_DN
ssl_client_verify_header = SSL_CLIENT_VERIFY
autosign = /etc/puppet/autosign.conf

[agent]
runinterval = 3000
EOF

cat > /etc/puppet/hiera.yaml <<EOF
:backends:
    - json
:hierarchy:
    - common
:yaml:
    :datadir: "/etc/puppet/environments/%{environment}/hiera"
:json:
    :datadir: "/etc/puppet/environments/%{environment}/hiera"
EOF

puppet apply bootstrap.pp && service apache2 restart

if [[ $? != 0 ]]; then
    echo 'bootstrap failed'
    exit 1
fi

puppet agent -t

if [[ $? != 0 ]]; then
    echo 'init puppet'
    exit 1
fi
puppet master --verbose --no-daemonize
if [[ $? != 0 ]];then
    echo "create cert failed"
    exit 1
fi
