#!/bin/bash
apt-get install -y puppet
AGENT_NAME=`hostname -f`
CERT_NAME="cert_$AGENT_NAME"
cat >  /etc/puppet/puppet.conf <<EOF
[main]
certname=$CERT_NAME
server=$1
environment=production
runinterval=1h
EOF
service puppet restart
puppet agent -t
